defaults:
  batch_size: 1
  max_retries: 3
  model: gpt-oss
  scenario: water_engineering
  timeout: 30
directories:
  index_files: ./results
  ocr_files: ./ocr_files
  temp_files: ./temp
indexing:
  if_add_doc_description: 'no'
  if_add_node_id: 'yes'
  if_add_node_summary: 'yes'
  if_add_node_text: 'no'
  max_page_num_each_node: 10
  toc_check_page_num: 20
models:
  ds-r1:
    api_key: b80d1503-8d91-4a98-affb-efc86890aad1
    base_url: https://ark.cn-beijing.volces.com/api/v3
    context_limit: 64000
    description: deepseek-r1-250528
    enabled: true
    max_tokens: 4000
    model_name: deepseek-r1-250528
    name: deepseek-r1-250528
    temperature: 0.1
  gpt-oss:
    api_key: QMcnWxkavgaW7QkPhHjGKqq_gCDIuhhRQqBf7hiqNdY
    base_url: https://api.poe.com/v1
    context_limit: 128000
    description: OpenAI gpt-oss
    enabled: true
    max_tokens: 4000
    model_name: GPT-OSS-120B-CS
    name: GPT-OSS-120B-CS
    temperature: 0.1
  qwen3-30b:
    api_key: QMcnWxkavgaW7QkPhHjGKqq_gCDIuhhRQqBf7hiqNdY
    base_url: https://api.poe.com/v1
    context_limit: 128000
    description: qwen3 30b
    enabled: true
    max_tokens: 4000
    model_name: Qwen3-30B-A3B-Instruct
    name: Qwen3-30B-A3B-Instruct
    temperature: 0.1
  qwen3-32b:
    api_key: QMcnWxkavgaW7QkPhHjGKqq_gCDIuhhRQqBf7hiqNdY
    base_url: https://api.poe.com/v1
    context_limit: 128000
    description: qwen3 32b
    enabled: true
    max_tokens: 4000
    model_name: Qwen3-32B-CS
    name: Qwen3-32B-CS
    temperature: 0.1
  qwen3-235b:
    api_key: QMcnWxkavgaW7QkPhHjGKqq_gCDIuhhRQqBf7hiqNdY
    base_url: https://api.poe.com/v1
    context_limit: 128000
    description: Qwen3-235B-2507-CS
    enabled: true
    max_tokens: 4000
    model_name: Qwen3-235B-2507-CS
    name: Qwen3-235B-2507-CS
    temperature: 0.1
scenarios:
  water_engineering:
    description: 适用于水利工程、水电站、水库等文档
    enabled: true
    name: 水利工程
