# PageIndex 提示词配置文件
# 支持不同场景和行业的提示词配置

scenarios:
  water_engineering:
    name: "水利工程"
    description: "适用于水利工程、水电站、水库等文档"
    
    structure_analysis: |
      请深入分析以下水利工程文档内容，创建细粒度的文档结构索引。这是一个包含大量技术参数、表格和图表的水利工程文档。

      文档内容样本：
      {document_sample}

      请返回以下格式的JSON：
      {
          "structure": [
              {
                  "title": "节点标题",
                  "start_page": 开始页码,
                  "end_page": 结束页码,
                  "summary": "节点摘要",
                  "has_tables": true/false,
                  "table_count": 表格数量估计,
                  "key_metrics": ["关键指标1", "关键指标2"],
                  "content_type": "节点类型",
                  "granularity": "细粒度级别"
              }
          ]
      }

      要求：
      1. 创建超细粒度索引，每个节点包含1-3页内容，不要超过3页
      2. 识别所有有意义的内容单元：
         - 工程概况和基本信息
         - 技术参数表格（每个重要表格单独成节点）
         - 运行数据表格（每个重要表格单独成节点）
         - 经济分析数据
         - 环境影响评估
         - 操作流程说明
         - 故障排除指南
         - 附录和参考资料
      3. 特别关注表格密集的页面，每个重要表格应该单独成节点
      4. 识别关键指标：库容、装机容量、发电量、水位、流量、投资、收益等
      5. 标注节点类型：overview(概述)、technical_specs(技术规格)、operational_data(运行数据)、economic_analysis(经济分析)、tables(表格数据)、procedures(操作流程)等
      6. 细粒度级别：high(高-单页或单表)、medium(中-2-3页)、low(低-3页)
      7. 对于208页包含213个表格的文档，应该创建80-150个超细粒度节点
      8. 每个水电站的概况、工程特性、工作表应该分别成节点
      9. 重要表格（如库容-水位关系、流量曲线、NHQ曲线等）应该单独成节点
      10. 必须返回有效的JSON格式，不要包含任何其他文字

    search_analysis: |
      请分析以下查询问题，找到最相关的文档章节。

      查询问题：{query}

      可用章节：
      {available_chapters}

      请直接返回以下格式的JSON，不要包含任何其他内容或标签：
      {
          "query_analysis": "查询意图分析",
          "search_strategy": "搜索策略说明",
          "relevant_chapters": [
              {
                  "chapter_id": "章节ID",
                  "relevance_score": 0.9,
                  "reason": "选择理由",
                  "expected_info": "期望找到的信息"
              }
          ]
      }

      重要：请只返回JSON格式，不要包含<think>、```等标签或额外说明。

      要求：
      1. 分析查询意图，理解用户想要获取什么信息
      2. 从可用章节中找到最相关的章节（最多3个）
      3. 为每个相关章节打分（0-1）
      4. 说明选择理由和期望找到的信息
      5. 必须返回有效的JSON格式

    answer_generation: |
      请基于以下文档内容回答用户问题。

      用户问题：{query}

      相关文档内容：
      {relevant_content}

      请提供准确、详细的回答：
      1. 直接回答用户问题
      2. 引用具体的数值、数据
      3. 如果涉及表格，说明表格位置
      4. 如果信息不完整，说明需要查看哪些章节
      5. 保持专业性和准确性

      回答：
